### ISSUE TITLE
Do you have any script to test on single image? 

### ISSUE THREAD

**Issue by ThiagoMateo** [neelabh17/MAVI-Face#1]
i have to comment 2 line of code (162, 169) in detect.py to run test on single image. But the result is not correct. 
![test](https://user-images.githubusercontent.com/48821989/80661232-47b6cf80-8ab8-11ea-91fc-817f50416256.jpg)

**Comment by neelabh17** [comment]
I am sorry, it contained some of my experiments.
I have updated the detect.py file. Do let me know if any other errors are still present.
I am actually working on a different branch with new features. I will be committing it in a few days. I am completing the documentation.

**Comment by bicycleman15** [comment]
@ThiagoMateo I'm assuming it worked for you. So I am closing this issue for now. You can always open this up again if you have any problems 😄
